"""Начальная схема

Revision ID: 8db1db33dc6b
Revises: 
Create Date: 2026-05-15 13:04:01.477071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db1db33dc6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('ozon_client_id', sa.String(length=64), nullable=True),
    sa.Column('ozon_api_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('sales_data', sa.JSON(), nullable=False),
    sa.Column('views_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_analytics_user_period', ['user_id', 'period'], unique=False)

    op.create_table('change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.create_index('ix_change_log_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_change_log_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_change_log_user_entity', ['user_id', 'entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_log_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ozon_order_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_orders_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_orders_user_ozon', ['user_id', 'ozon_order_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ozon_product_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_products_user_ozon', ['user_id', 'ozon_product_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reports_user_type', ['user_id', 'report_type'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('tracking_number', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_shipments_user_order', ['user_id', 'order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index('ix_shipments_user_order')
        batch_op.drop_index(batch_op.f('ix_shipments_user_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_order_id'))

    op.drop_table('shipments')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_user_type')
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_user_ozon')
        batch_op.drop_index(batch_op.f('ix_products_user_id'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_user_ozon')
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index('ix_orders_user_created')
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_log_user_id'))
        batch_op.drop_index('ix_change_log_user_entity')
        batch_op.drop_index('ix_change_log_timestamp')
        batch_op.drop_index('ix_change_log_entity')

    op.drop_table('change_log')
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index('ix_analytics_user_period')
        batch_op.drop_index(batch_op.f('ix_analytics_user_id'))

    op.drop_table('analytics')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
