"""Release notes журнал обновлений

Revision ID: c465c4ae8c90
Revises: f9c471b76846
Create Date: 2026-05-15 14:11:27.124600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c465c4ae8c90'
down_revision = 'f9c471b76846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('released_at', sa.Date(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('release_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_notes_released_at'), ['released_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_notes_version'), ['version'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_notes_version'))
        batch_op.drop_index(batch_op.f('ix_release_notes_released_at'))

    op.drop_table('release_notes')
    # ### end Alembic commands ###
