"""Ozon статус подключения

Revision ID: f9c471b76846
Revises: 7928dc5f74dd
Create Date: 2026-05-15 13:45:58.064325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c471b76846'
down_revision = '7928dc5f74dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ozon_company_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('ozon_connected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('ozon_key_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ozon_key_active')
        batch_op.drop_column('ozon_connected_at')
        batch_op.drop_column('ozon_company_name')

    # ### end Alembic commands ###
